# .scrutinizer.yml
filter:
    excluded_paths:
        - tests/*

build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=clover.xml'
                coverage:
                    file: 'clover.xml'
                    format: 'clover'
